In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train = pd.read_csv('/kaggle/NewsClassification/Train.csv')
df_test = pd.read_csv('/kaggle/NewsClassification/Test.csv')
df_sub = pd.read_csv('/kaggle/NewsClassification/sample.csv')

In [3]:
df_train

        Id                                           Headline   Category
0        1           Breakthrough discovery in cyber research    Science
1        2   Government focuses on youth development programs    Society
2        3   health party wins majority in assembly elections   Politics
3        4  Startups in digital sector attract global inve...   Business
4        5  Sensex surges by technology points amid market...   Business
...    ...                                                ...        ...
4995  4996  Startups in women sector attract global investors   Business
4996  4997       CBSE implements space curriculum for schools  Education
4997  4998     India achieves milestone in finance technology    Science
4998  4999           India signs trade deal with river nation   Business
4999  5000       BCCI announces schedule for cyber tournament     Sports

[5000 rows x 3 columns]

In [4]:
df_test

        Id                                           Headline
0        1           RBI announces new women policy framework
1        2            PM inaugurates climate project in Delhi
2        3  Government launches finance scholarship for st...
3        4   WHO praises Indiaâ€™s efforts in combating space
4        5  Indian music festival in sports draws massive ...
...    ...                                                ...
1995  1996    Indian startup develops river app for education
1996  1997      CSIR scientists discover new finance compound
1997  1998  Infosys partners with digital for technology a...
1998  1999       CSIR scientists discover new health compound
1999  2000  Indian womenâ€™s team secures victory in women...

[2000 rows x 2 columns]

In [5]:
X = df_train['Headline']
y = df_train['Category']
X_test = df_test['Headline']

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
from sklearn.model_selection import GridSearchCV

In [8]:
from sklearn.pipeline import Pipeline

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
model = RandomForestClassifier()

In [11]:
pipe = Pipeline([('tfidf', TfidfVectorizer()), ('model', model)])

In [17]:
params = {
    'tfidf__max_features': [1000, 3000, 5000],
    'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)],
    'model__n_estimators': [100, 200],
    'model__max_depth': [10, 20, 30],
    'model__min_samples_split': [2, 5],
    'model__min_samples_leaf': [1, 2, 4]
}

In [18]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [19]:
final_model.fit(X, y)

Fitting 3 folds for each of 324 candidates, totalling 972 fits
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('tfidf', TfidfVectorizer()),
                                       ('model', RandomForestClassifier())]),
             param_grid={'model__max_depth': [10, 20, 30],
                         'model__min_samples_leaf': [1, 2, 4],
                         'model__min_samples_split': [2, 5],
                         'model__n_estimators': [100, 200],
                         'tfidf__max_features': [1000, 3000, 5000],
                         'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)]},
             verbose=2)

In [20]:
y_pred = final_model.predict(X_test)

In [58]:
new_df = pd.DataFrame(columns = ['id', 'category'])

In [59]:
new_df['id'] = np.arange(1,2001)

In [56]:
new_df.drop('category', axis=1)

        id
0        1
1        2
2        3
3        4
4        5
...    ...
1994  1995
1995  1996
1996  1997
1997  1998
1998  1999

[1999 rows x 1 columns]

In [60]:
new_df['category'] = y_pred

In [62]:
new_df

        id       category
0        1       Business
1        2       Politics
2        3      Education
3        4         Health
4        5  Entertainment
...    ...            ...
1995  1996     Technology
1996  1997        Science
1997  1998     Technology
1998  1999        Science
1999  2000         Sports

[2000 rows x 2 columns]

In [61]:
new_df.to_csv('sub.csv', index=False, index_label=False)